# This file has been generated by the GUI designer. Do not modify.
class FrmCadExtensao(object):
	def __init__(self):

	def Build(self):
		Stetic.Gui.Initialize(self)
		# Widget HFSGuardaDiretorio.gui.FrmCadExtensao
		self._UIManager = Gtk.UIManager()
		w1 = Gtk.ActionGroup("Default")
		self._ExtensaoAction = Gtk.Action("ExtensaoAction", Mono.Unix.Catalog.GetString("Extensão"), None, None)
		self._ExtensaoAction.ShortLabel = Mono.Unix.Catalog.GetString("Extensão")
		w1.Add(self._ExtensaoAction, None)
		self._IncluirExtensoAction = Gtk.Action("IncluirExtensoAction", Mono.Unix.Catalog.GetString("Incluir Extensão"), None, None)
		self._IncluirExtensoAction.ShortLabel = Mono.Unix.Catalog.GetString("Incluir Extensão")
		w1.Add(self._IncluirExtensoAction, None)
		self._ExcluirExtensaoAction = Gtk.Action("ExcluirExtensaoAction", Mono.Unix.Catalog.GetString("Excluir Extensão"), None, None)
		self._ExcluirExtensaoAction.ShortLabel = Mono.Unix.Catalog.GetString("Excluir Extensão")
		w1.Add(self._ExcluirExtensaoAction, None)
		self._ExcluirTodasExtensoesAction = Gtk.Action("ExcluirTodasExtensoesAction", Mono.Unix.Catalog.GetString("Excluir Todas Extensões"), None, None)
		self._ExcluirTodasExtensoesAction.ShortLabel = Mono.Unix.Catalog.GetString("Excluir Todas Extensões")
		w1.Add(self._ExcluirTodasExtensoesAction, None)
		self._ExportarTodosAction = Gtk.Action("ExportarTodosAction", Mono.Unix.Catalog.GetString("Exportar Todos"), None, None)
		self._ExportarTodosAction.ShortLabel = Mono.Unix.Catalog.GetString("Exportar Todos")
		w1.Add(self._ExportarTodosAction, None)
		self._ExportarParaBitmapAction = Gtk.Action("ExportarParaBitmapAction", Mono.Unix.Catalog.GetString("Exportar para Bitmap"), None, None)
		self._ExportarParaBitmapAction.ShortLabel = Mono.Unix.Catalog.GetString("Exportar para Bitmap")
		w1.Add(self._ExportarParaBitmapAction, None)
		self._ExportarParaIConeAction = Gtk.Action("ExportarParaIConeAction", Mono.Unix.Catalog.GetString("Exportar para Ícone"), None, None)
		self._ExportarParaIConeAction.ShortLabel = Mono.Unix.Catalog.GetString("Exportar para Ícone")
		w1.Add(self._ExportarParaIConeAction, None)
		self._ExportarParaGIFAction = Gtk.Action("ExportarParaGIFAction", Mono.Unix.Catalog.GetString("Exportar para GIF"), None, None)
		self._ExportarParaGIFAction.ShortLabel = Mono.Unix.Catalog.GetString("Exportar para GIF")
		w1.Add(self._ExportarParaGIFAction, None)
		self._ExportarParaJPEGAction = Gtk.Action("ExportarParaJPEGAction", Mono.Unix.Catalog.GetString("Exportar para JPEG"), None, None)
		self._ExportarParaJPEGAction.ShortLabel = Mono.Unix.Catalog.GetString("Exportar para JPEG")
		w1.Add(self._ExportarParaJPEGAction, None)
		self._ExportarParaPNGAction = Gtk.Action("ExportarParaPNGAction", Mono.Unix.Catalog.GetString("Exportar para PNG"), None, None)
		self._ExportarParaPNGAction.ShortLabel = Mono.Unix.Catalog.GetString("Exportar para PNG")
		w1.Add(self._ExportarParaPNGAction, None)
		self._ExportarParaTIFFAction = Gtk.Action("ExportarParaTIFFAction", Mono.Unix.Catalog.GetString("Exportar para TIFF"), None, None)
		self._ExportarParaTIFFAction.ShortLabel = Mono.Unix.Catalog.GetString("Exportar para TIFF")
		w1.Add(self._ExportarParaTIFFAction, None)
		self._ImportarTodosAction = Gtk.Action("ImportarTodosAction", Mono.Unix.Catalog.GetString("Importar Todos"), None, None)
		self._ImportarTodosAction.ShortLabel = Mono.Unix.Catalog.GetString("Importar Todos")
		w1.Add(self._ImportarTodosAction, None)
		self._ImportarIconesDosArquivosAction = Gtk.Action("ImportarIconesDosArquivosAction", Mono.Unix.Catalog.GetString("Importar Ícones dos Arquivos"), None, None)
		self._ImportarIconesDosArquivosAction.ShortLabel = Mono.Unix.Catalog.GetString("Importar Ícones dos Arquivos")
		w1.Add(self._ImportarIconesDosArquivosAction, None)
		self._ExtrairIconesDosArquivosAction = Gtk.Action("ExtrairIconesDosArquivosAction", Mono.Unix.Catalog.GetString("Extrair Ícones dos Arquivos"), None, None)
		self._ExtrairIconesDosArquivosAction.ShortLabel = Mono.Unix.Catalog.GetString("Extrair Ícones dos Arquivos")
		w1.Add(self._ExtrairIconesDosArquivosAction, None)
		self._UIManager.InsertActionGroup(w1, 0)
		self.AddAccelGroup(self._UIManager.AccelGroup)
		self._WidthRequest = 286
		self._HeightRequest = 418
		self._Name = "HFSGuardaDiretorio.gui.FrmCadExtensao"
		self._Title = Mono.Unix.Catalog.GetString("Cadastro de Extensão de Arquivo")
		self._WindowPosition = ((1))
		self._Modal = True
		self._Resizable = False
		self._AllowGrow = False
		# Internal child HFSGuardaDiretorio.gui.FrmCadExtensao.VBox
		w2 = self._VBox
		w2.Name = "dialog1_VBox"
		w2.BorderWidth = ((2))
		# Container child dialog1_VBox.Gtk.Box+BoxChild
		self._vbox3 = Gtk.VBox()
		self._vbox3.Name = "vbox3"
		self._vbox3.Spacing = 6
		# Container child vbox3.Gtk.Box+BoxChild
		self._UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='ExtensaoAction' action='ExtensaoAction'><menuitem name='IncluirExtensoAction' action='IncluirExtensoAction'/><menuitem name='ExcluirExtensaoAction' action='ExcluirExtensaoAction'/><menuitem name='ExcluirTodasExtensoesAction' action='ExcluirTodasExtensoesAction'/></menu><menu name='ExportarTodosAction' action='ExportarTodosAction'><menuitem name='ExportarParaBitmapAction' action='ExportarParaBitmapAction'/><menuitem name='ExportarParaIConeAction' action='ExportarParaIConeAction'/><menuitem name='ExportarParaGIFAction' action='ExportarParaGIFAction'/><menuitem name='ExportarParaJPEGAction' action='ExportarParaJPEGAction'/><menuitem name='ExportarParaPNGAction' action='ExportarParaPNGAction'/><menuitem name='ExportarParaTIFFAction' action='ExportarParaTIFFAction'/></menu><menu name='ImportarTodosAction' action='ImportarTodosAction'><menuitem name='ImportarIconesDosArquivosAction' action='ImportarIconesDosArquivosAction'/><menuitem name='ExtrairIconesDosArquivosAction' action='ExtrairIconesDosArquivosAction'/></menu></menubar></ui>")
		self._menubar1 = ((self._UIManager.GetWidget("/menubar1")))
		self._menubar1.Name = "menubar1"
		self._vbox3.Add(self._menubar1)
		w3 = ((self._vbox3[self._menubar1]))
		w3.Position = 0
		w3.Expand = False
		w3.Fill = False
		# Container child vbox3.Gtk.Box+BoxChild
		self._GtkScrolledWindow = Gtk.ScrolledWindow()
		self._GtkScrolledWindow.Name = "GtkScrolledWindow"
		self._GtkScrolledWindow.ShadowType = ((1))
		# Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		self._tabelaExtensao = Gtk.NodeView()
		self._tabelaExtensao.CanFocus = True
		self._tabelaExtensao.Name = "tabelaExtensao"
		self._GtkScrolledWindow.Add(self._tabelaExtensao)
		self._vbox3.Add(self._GtkScrolledWindow)
		w5 = ((self._vbox3[self._GtkScrolledWindow]))
		w5.Position = 1
		w2.Add(self._vbox3)
		w6 = ((w2[self._vbox3]))
		w6.Position = 0
		# Internal child HFSGuardaDiretorio.gui.FrmCadExtensao.ActionArea
		w7 = self._ActionArea
		w7.Name = "dialog1_ActionArea"
		w7.Spacing = 10
		w7.BorderWidth = ((5))
		w7.LayoutStyle = ((1))
		# Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
		self._btnIncluir = Gtk.Button()
		self._btnIncluir.CanDefault = True
		self._btnIncluir.CanFocus = True
		self._btnIncluir.Name = "btnIncluir"
		self._btnIncluir.UseUnderline = True
		self._btnIncluir.Label = Mono.Unix.Catalog.GetString("_Incluir")
		self.AddActionWidget(self._btnIncluir, 0)
		w8 = ((w7[self._btnIncluir]))
		w8.Expand = False
		w8.Fill = False
		# Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
		self._btnExcluir = Gtk.Button()
		self._btnExcluir.CanDefault = True
		self._btnExcluir.CanFocus = True
		self._btnExcluir.Name = "btnExcluir"
		self._btnExcluir.UseUnderline = True
		self._btnExcluir.Label = Mono.Unix.Catalog.GetString("_Excluir")
		self.AddActionWidget(self._btnExcluir, 0)
		w9 = ((w7[self._btnExcluir]))
		w9.Position = 1
		w9.Expand = False
		w9.Fill = False
		if (self._Child != None):
			self._Child.ShowAll()
		self._DefaultWidth = 400
		self._DefaultHeight = 418
		self.Show()
		self._IncluirExtensoAction.Activated += self._OnIncluirExtensaoActionActivated
		self._ExcluirExtensaoAction.Activated += self._OnExcluirExtensaoActionActivated
		self._ExcluirTodasExtensoesAction.Activated += self._OnExcluirTodasExtensoesActionActivated
		self._ExportarParaBitmapAction.Activated += self._OnExportarParaBitmapActionActivated
		self._ExportarParaIConeAction.Activated += self._OnExportarParaIConeActionActivated
		self._ExportarParaGIFAction.Activated += self._OnExportarParaGIFActionActivated
		self._ExportarParaJPEGAction.Activated += self._OnExportarParaJPEGActionActivated
		self._ExportarParaPNGAction.Activated += self._OnExportarParaPNGActionActivated
		self._ExportarParaTIFFAction.Activated += self._OnExportarParaTIFFActionActivated
		self._ImportarIconesDosArquivosAction.Activated += self._OnImportarIconesDosArquivosActionActivated
		self._ExtrairIconesDosArquivosAction.Activated += self._OnExtrairIconesDosArquivosActionActivated
		self._btnIncluir.Clicked += self._OnBtnIncluirClicked
		self._btnExcluir.Clicked += self._OnBtnExcluirClicked