# This file has been generated by the GUI designer. Do not modify.
class FrmInfoDiretorio(object):
	def __init__(self):

	def Build(self):
		Stetic.Gui.Initialize(self)
		# Widget HFSGuardaDiretorio.gui.FrmInfoDiretorio
		self._WidthRequest = 369
		self._HeightRequest = 372
		self._Name = "HFSGuardaDiretorio.gui.FrmInfoDiretorio"
		self._Title = Mono.Unix.Catalog.GetString("Informações do Diretório / Arquivo")
		self._WindowPosition = ((1))
		self._Modal = True
		# Internal child HFSGuardaDiretorio.gui.FrmInfoDiretorio.VBox
		w1 = self._VBox
		w1.Name = "dialog1_VBox"
		w1.BorderWidth = ((2))
		# Container child dialog1_VBox.Gtk.Box+BoxChild
		self._vbox4 = Gtk.VBox()
		self._vbox4.Name = "vbox4"
		self._vbox4.Spacing = 6
		# Container child vbox4.Gtk.Box+BoxChild
		self._frame1 = Gtk.Frame()
		self._frame1.Name = "frame1"
		# Container child frame1.Gtk.Container+ContainerChild
		self._GtkAlignment1 = Gtk.Alignment(0f, 0f, 1f, 1f)
		self._GtkAlignment1.Name = "GtkAlignment1"
		self._GtkAlignment1.LeftPadding = ((12))
		# Container child GtkAlignment1.Gtk.Container+ContainerChild
		self._table1 = Gtk.Table(((3)), ((2)), True)
		self._table1.Name = "table1"
		self._table1.RowSpacing = ((6))
		self._table1.ColumnSpacing = ((6))
		# Container child table1.Gtk.Table+TableChild
		self._label1 = Gtk.Label()
		self._label1.Name = "label1"
		self._label1.LabelProp = Mono.Unix.Catalog.GetString("[ARQ] - Arquivo comum")
		self._table1.Add(self._label1)
		w2 = ((self._table1[self._label1]))
		w2.XOptions = ((4))
		w2.YOptions = ((4))
		# Container child table1.Gtk.Table+TableChild
		self._label2 = Gtk.Label()
		self._label2.Name = "label2"
		self._label2.LabelProp = Mono.Unix.Catalog.GetString("[DIR] - Diretório")
		self._table1.Add(self._label2)
		w3 = ((self._table1[self._label2]))
		w3.LeftAttach = ((1))
		w3.RightAttach = ((2))
		w3.XOptions = ((4))
		w3.YOptions = ((4))
		# Container child table1.Gtk.Table+TableChild
		self._label3 = Gtk.Label()
		self._label3.Name = "label3"
		self._label3.LabelProp = Mono.Unix.Catalog.GetString("[HID] - Arquivo Oculto")
		self._table1.Add(self._label3)
		w4 = ((self._table1[self._label3]))
		w4.TopAttach = ((1))
		w4.BottomAttach = ((2))
		w4.XOptions = ((4))
		w4.YOptions = ((4))
		# Container child table1.Gtk.Table+TableChild
		self._label4 = Gtk.Label()
		self._label4.Name = "label4"
		self._label4.LabelProp = Mono.Unix.Catalog.GetString("[VOL] - Volume ID")
		self._table1.Add(self._label4)
		w5 = ((self._table1[self._label4]))
		w5.TopAttach = ((1))
		w5.BottomAttach = ((2))
		w5.LeftAttach = ((1))
		w5.RightAttach = ((2))
		w5.XOptions = ((4))
		w5.YOptions = ((4))
		# Container child table1.Gtk.Table+TableChild
		self._label5 = Gtk.Label()
		self._label5.Name = "label5"
		self._label5.LabelProp = Mono.Unix.Catalog.GetString("[SYS] - Arquivo de Sistema")
		self._table1.Add(self._label5)
		w6 = ((self._table1[self._label5]))
		w6.TopAttach = ((2))
		w6.BottomAttach = ((3))
		w6.XOptions = ((4))
		w6.YOptions = ((4))
		# Container child table1.Gtk.Table+TableChild
		self._label6 = Gtk.Label()
		self._label6.Name = "label6"
		self._label6.LabelProp = Mono.Unix.Catalog.GetString("[ROL] - Arquivo Somente Leitura")
		self._table1.Add(self._label6)
		w7 = ((self._table1[self._label6]))
		w7.TopAttach = ((2))
		w7.BottomAttach = ((3))
		w7.LeftAttach = ((1))
		w7.RightAttach = ((2))
		w7.XOptions = ((4))
		w7.YOptions = ((4))
		self._GtkAlignment1.Add(self._table1)
		self._frame1.Add(self._GtkAlignment1)
		self._GtkLabel1 = Gtk.Label()
		self._GtkLabel1.Name = "GtkLabel1"
		self._GtkLabel1.UseMarkup = True
		self._frame1.LabelWidget = self._GtkLabel1
		self._vbox4.Add(self._frame1)
		w10 = ((self._vbox4[self._frame1]))
		w10.Position = 0
		w10.Expand = False
		w10.Fill = False
		# Container child vbox4.Gtk.Box+BoxChild
		self._GtkScrolledWindow = Gtk.ScrolledWindow()
		self._GtkScrolledWindow.Name = "GtkScrolledWindow"
		self._GtkScrolledWindow.ShadowType = ((1))
		# Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		self._tabelaInfo = Gtk.NodeView()
		self._tabelaInfo.CanFocus = True
		self._tabelaInfo.Name = "tabelaInfo"
		self._GtkScrolledWindow.Add(self._tabelaInfo)
		self._vbox4.Add(self._GtkScrolledWindow)
		w12 = ((self._vbox4[self._GtkScrolledWindow]))
		w12.Position = 1
		w1.Add(self._vbox4)
		w13 = ((w1[self._vbox4]))
		w13.Position = 0
		# Internal child HFSGuardaDiretorio.gui.FrmInfoDiretorio.ActionArea
		w14 = self._ActionArea
		w14.Name = "dialog1_ActionArea"
		w14.Spacing = 10
		w14.BorderWidth = ((5))
		w14.LayoutStyle = ((1))
		# Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
		self._btnOk = Gtk.Button()
		self._btnOk.CanDefault = True
		self._btnOk.CanFocus = True
		self._btnOk.Name = "btnOk"
		self._btnOk.UseStock = True
		self._btnOk.UseUnderline = True
		self._btnOk.Label = "gtk-ok"
		self.AddActionWidget(self._btnOk, -5)
		w15 = ((w14[self._btnOk]))
		w15.Expand = False
		w15.Fill = False
		if (self._Child != None):
			self._Child.ShowAll()
		self._DefaultWidth = 400
		self._DefaultHeight = 372
		self.Show()
		self._btnOk.Clicked += self._OnBtnOkClicked