# This file has been generated by the GUI designer. Do not modify.
class FrmSplash(object):
	def __init__(self):

	def Build(self):
		Stetic.Gui.Initialize(self)
		# Widget HFSGuardaDiretorio.gui.FrmSplash
		self._Name = "HFSGuardaDiretorio.gui.FrmSplash"
		self._Title = Mono.Unix.Catalog.GetString("FrmSplash")
		self._TypeHint = ((4))
		self._WindowPosition = ((3))
		self._Modal = True
		self._Resizable = False
		self._AllowGrow = False
		self._DefaultWidth = 375
		self._DefaultHeight = 113
		self._Decorated = False
		# Container child HFSGuardaDiretorio.gui.FrmSplash.Gtk.Container+ContainerChild
		self._vbox2 = Gtk.VBox()
		self._vbox2.Name = "vbox2"
		self._vbox2.Spacing = 6
		self._vbox2.BorderWidth = ((1))
		# Container child vbox2.Gtk.Box+BoxChild
		self._label1 = Gtk.Label()
		self._label1.Name = "label1"
		self._label1.LabelProp = Mono.Unix.Catalog.GetString("HFSGuardaDiretorio 2.0")
		self._vbox2.Add(self._label1)
		w1 = ((self._vbox2[self._label1]))
		w1.Position = 0
		w1.Expand = False
		w1.Fill = False
		# Container child vbox2.Gtk.Box+BoxChild
		self._label2 = Gtk.Label()
		self._label2.Name = "label2"
		self._label2.LabelProp = Mono.Unix.Catalog.GetString("Catalogador de Diretórios")
		self._vbox2.Add(self._label2)
		w2 = ((self._vbox2[self._label2]))
		w2.Position = 1
		w2.Expand = False
		w2.Fill = False
		# Container child vbox2.Gtk.Box+BoxChild
		self._pb = Gtk.ProgressBar()
		self._pb.Name = "pb"
		self._vbox2.Add(self._pb)
		w3 = ((self._vbox2[self._pb]))
		w3.Position = 2
		w3.Expand = False
		w3.Fill = False
		self.Add(self._vbox2)
		if (self._Child != None):
			self._Child.ShowAll()
		self.Show()