# This file has been generated by the GUI designer. Do not modify.
class FrmImportarDiretorio(object):
	def __init__(self):

	def Build(self):
		Stetic.Gui.Initialize(self)
		# Widget HFSGuardaDiretorio.gui.FrmImportarDiretorio
		self._WidthRequest = 895
		self._HeightRequest = 572
		self._Name = "HFSGuardaDiretorio.gui.FrmImportarDiretorio"
		self._Title = Mono.Unix.Catalog.GetString("Importando Diretório")
		self._TypeHint = ((4))
		self._WindowPosition = ((1))
		self._Modal = True
		self._Resizable = False
		self._AllowGrow = False
		# Container child HFSGuardaDiretorio.gui.FrmImportarDiretorio.Gtk.Container+ContainerChild
		self._vbox1 = Gtk.VBox()
		self._vbox1.Name = "vbox1"
		self._vbox1.Spacing = 6
		# Container child vbox1.Gtk.Box+BoxChild
		self._GtkScrolledWindow = Gtk.ScrolledWindow()
		self._GtkScrolledWindow.Name = "GtkScrolledWindow"
		self._GtkScrolledWindow.ShadowType = ((1))
		# Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		self._memoImportaDir = Gtk.TextView()
		self._memoImportaDir.CanFocus = True
		self._memoImportaDir.Name = "memoImportaDir"
		self._memoImportaDir.Editable = False
		self._memoImportaDir.CursorVisible = False
		self._memoImportaDir.AcceptsTab = False
		self._GtkScrolledWindow.Add(self._memoImportaDir)
		self._vbox1.Add(self._GtkScrolledWindow)
		w2 = ((self._vbox1[self._GtkScrolledWindow]))
		w2.Position = 0
		# Container child vbox1.Gtk.Box+BoxChild
		self._pbImportar = Gtk.ProgressBar()
		self._pbImportar.Name = "pbImportar"
		self._vbox1.Add(self._pbImportar)
		w3 = ((self._vbox1[self._pbImportar]))
		w3.Position = 1
		w3.Expand = False
		w3.Fill = False
		# Container child vbox1.Gtk.Box+BoxChild
		self._hbox3 = Gtk.HBox()
		self._hbox3.Name = "hbox3"
		self._hbox3.Spacing = 6
		# Container child hbox3.Gtk.Box+BoxChild
		self._barraStatus1 = Gtk.Statusbar()
		self._barraStatus1.Name = "barraStatus1"
		self._barraStatus1.Spacing = 6
		self._barraStatus1.HasResizeGrip = False
		self._hbox3.Add(self._barraStatus1)
		w4 = ((self._hbox3[self._barraStatus1]))
		w4.Position = 0
		w4.Expand = False
		# Container child hbox3.Gtk.Box+BoxChild
		self._barraStatus2 = Gtk.Statusbar()
		self._barraStatus2.Name = "barraStatus2"
		self._barraStatus2.Spacing = 6
		self._hbox3.Add(self._barraStatus2)
		w5 = ((self._hbox3[self._barraStatus2]))
		w5.Position = 1
		self._vbox1.Add(self._hbox3)
		w6 = ((self._vbox1[self._hbox3]))
		w6.Position = 2
		w6.Expand = False
		w6.Fill = False
		self.Add(self._vbox1)
		if (self._Child != None):
			self._Child.ShowAll()
		self._DefaultWidth = 895
		self._DefaultHeight = 572
		self.Show()