
// This file has been generated by the GUI designer. Do not modify.
namespace HFSGuardaDiretorio.gui
{
	public partial class FrmImportarDiretorio
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView memoImportaDir;
		
		private global::Gtk.ProgressBar pbImportar;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Statusbar barraStatus1;
		
		private global::Gtk.Statusbar barraStatus2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget HFSGuardaDiretorio.gui.FrmImportarDiretorio
			this.WidthRequest = 895;
			this.HeightRequest = 572;
			this.Name = "HFSGuardaDiretorio.gui.FrmImportarDiretorio";
			this.Title = global::Mono.Unix.Catalog.GetString ("Importando Diretório");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(4));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child HFSGuardaDiretorio.gui.FrmImportarDiretorio.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.memoImportaDir = new global::Gtk.TextView ();
			this.memoImportaDir.CanFocus = true;
			this.memoImportaDir.Name = "memoImportaDir";
			this.memoImportaDir.Editable = false;
			this.memoImportaDir.CursorVisible = false;
			this.memoImportaDir.AcceptsTab = false;
			this.GtkScrolledWindow.Add (this.memoImportaDir);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.pbImportar = new global::Gtk.ProgressBar ();
			this.pbImportar.Name = "pbImportar";
			this.vbox1.Add (this.pbImportar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.pbImportar]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.barraStatus1 = new global::Gtk.Statusbar ();
			this.barraStatus1.Name = "barraStatus1";
			this.barraStatus1.Spacing = 6;
			this.barraStatus1.HasResizeGrip = false;
			this.hbox3.Add (this.barraStatus1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.barraStatus1]));
			w4.Position = 0;
			w4.Expand = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.barraStatus2 = new global::Gtk.Statusbar ();
			this.barraStatus2.Name = "barraStatus2";
			this.barraStatus2.Spacing = 6;
			this.hbox3.Add (this.barraStatus2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.barraStatus2]));
			w5.Position = 1;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 895;
			this.DefaultHeight = 572;
			this.Show ();
		}
	}
}
