
// This file has been generated by the GUI designer. Do not modify.
namespace HFSGuardaDiretorio.gui
{
	public partial class FrmCompararDiretorio
	{
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button btnCompararDiretorios;
		
		private global::Gtk.ProgressBar pb;
		
		private global::Gtk.Button btnSalvarLog;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.ComboBox cmbAba1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView tvDiretorio1;
		
		private global::Gtk.Label GtkLabel2;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.ComboBox cmbAba2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TreeView tvDiretorio2;
		
		private global::Gtk.Label GtkLabel3;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label labDiferencasEncontradas;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		
		private global::Gtk.NodeView tabelaCompara;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Statusbar barraStatus1;
		
		private global::Gtk.Statusbar barraStatus2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget HFSGuardaDiretorio.gui.FrmCompararDiretorio
			this.WidthRequest = 693;
			this.HeightRequest = 608;
			this.Name = "HFSGuardaDiretorio.gui.FrmCompararDiretorio";
			this.Title = global::Mono.Unix.Catalog.GetString ("Comparar Diretórios");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			this.AllowGrow = false;
			// Container child HFSGuardaDiretorio.gui.FrmCompararDiretorio.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnCompararDiretorios = new global::Gtk.Button ();
			this.btnCompararDiretorios.CanFocus = true;
			this.btnCompararDiretorios.Name = "btnCompararDiretorios";
			this.btnCompararDiretorios.UseUnderline = true;
			this.btnCompararDiretorios.Label = global::Mono.Unix.Catalog.GetString ("Comparar Diretórios");
			this.hbox1.Add (this.btnCompararDiretorios);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnCompararDiretorios]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.pb = new global::Gtk.ProgressBar ();
			this.pb.Name = "pb";
			this.hbox1.Add (this.pb);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.pb]));
			w2.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnSalvarLog = new global::Gtk.Button ();
			this.btnSalvarLog.CanFocus = true;
			this.btnSalvarLog.Name = "btnSalvarLog";
			this.btnSalvarLog.UseUnderline = true;
			this.btnSalvarLog.Label = global::Mono.Unix.Catalog.GetString ("Salvar Log");
			this.hbox1.Add (this.btnSalvarLog);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnSalvarLog]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.cmbAba1 = global::Gtk.ComboBox.NewText ();
			this.cmbAba1.Name = "cmbAba1";
			this.vbox4.Add (this.cmbAba1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.cmbAba1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvDiretorio1 = new global::Gtk.TreeView ();
			this.tvDiretorio1.CanFocus = true;
			this.tvDiretorio1.Name = "tvDiretorio1";
			this.GtkScrolledWindow.Add (this.tvDiretorio1);
			this.vbox4.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow]));
			w7.Position = 1;
			this.GtkAlignment.Add (this.vbox4);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Diretório 1</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel2;
			this.hbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.frame1]));
			w10.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.cmbAba2 = global::Gtk.ComboBox.NewText ();
			this.cmbAba2.Name = "cmbAba2";
			this.vbox5.Add (this.cmbAba2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.cmbAba2]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.tvDiretorio2 = new global::Gtk.TreeView ();
			this.tvDiretorio2.CanFocus = true;
			this.tvDiretorio2.Name = "tvDiretorio2";
			this.GtkScrolledWindow1.Add (this.tvDiretorio2);
			this.vbox5.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.GtkScrolledWindow1]));
			w13.Position = 1;
			this.GtkAlignment1.Add (this.vbox5);
			this.frame2.Add (this.GtkAlignment1);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Diretório 2</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel3;
			this.hbox2.Add (this.frame2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.frame2]));
			w16.Position = 1;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w17.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.labDiferencasEncontradas = new global::Gtk.Label ();
			this.labDiferencasEncontradas.Name = "labDiferencasEncontradas";
			this.labDiferencasEncontradas.LabelProp = global::Mono.Unix.Catalog.GetString ("Diferenças Encontradas");
			this.hbox3.Add (this.labDiferencasEncontradas);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.labDiferencasEncontradas]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.tabelaCompara = new global::Gtk.NodeView ();
			this.tabelaCompara.CanFocus = true;
			this.tabelaCompara.Name = "tabelaCompara";
			this.GtkScrolledWindow2.Add (this.tabelaCompara);
			this.vbox3.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow2]));
			w21.Position = 3;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.barraStatus1 = new global::Gtk.Statusbar ();
			this.barraStatus1.Name = "barraStatus1";
			this.barraStatus1.Spacing = 6;
			this.barraStatus1.HasResizeGrip = false;
			this.hbox4.Add (this.barraStatus1);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.barraStatus1]));
			w22.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.barraStatus2 = new global::Gtk.Statusbar ();
			this.barraStatus2.Name = "barraStatus2";
			this.barraStatus2.Spacing = 6;
			this.hbox4.Add (this.barraStatus2);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.barraStatus2]));
			w23.Position = 1;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
			w24.PackType = ((global::Gtk.PackType)(1));
			w24.Position = 4;
			w24.Expand = false;
			w24.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 693;
			this.DefaultHeight = 608;
			this.Show ();
			this.btnCompararDiretorios.Clicked += new global::System.EventHandler (this.OnBtnCompararDiretoriosClicked);
			this.btnSalvarLog.Clicked += new global::System.EventHandler (this.OnBtnSalvarLogClicked);
			this.cmbAba1.Changed += new global::System.EventHandler (this.OnCmbAba1Changed);
			this.cmbAba2.Changed += new global::System.EventHandler (this.OnCmbAba2Changed);
		}
	}
}
