
// This file has been generated by the GUI designer. Do not modify.
namespace HFSGuardaDiretorio.gui
{
	public partial class FrmPrincipal
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action AbaAction;
		
		private global::Gtk.Action DiretorioAction;
		
		private global::Gtk.Action VisaoAction;
		
		private global::Gtk.Action SobreAction;
		
		private global::Gtk.Action IncluirNovaAbaAction;
		
		private global::Gtk.Action AlterarNomeDaAbaAtivaAction;
		
		private global::Gtk.Action ExcluirAbaAtivaAction;
		
		private global::Gtk.Action ImportarDiretorioAction;
		
		private global::Gtk.Action ImportarSubDiretoriosAction;
		
		private global::Gtk.Action CompararDiretoriosAction;
		
		private global::Gtk.Action CadastrarExtensaoDeArquivoAction;
		
		private global::Gtk.Action Action;
		
		private global::Gtk.Action ExpandirDiretoriosAction;
		
		private global::Gtk.Action ColapsarDiretoriosAction;
		
		private global::Gtk.Action ExportarDiretoriosDaAbaAtivaAction;
		
		private global::Gtk.Action ImportarDiretoriosViaXMLAction;
		
		private global::Gtk.ToggleAction GravarLogDaImportacaoAction;
		
		private global::Gtk.Action TXTAction;
		
		private global::Gtk.Action TXTAction1;
		
		private global::Gtk.Action CSVAction;
		
		private global::Gtk.Action HTMLAction;
		
		private global::Gtk.Action XMLAction;
		
		private global::Gtk.Action SQLAction;
		
		private global::Gtk.Action MostrarOcultarArvoreDirAbaAtivaAction;
		
		private global::Gtk.Action MostrarOcultarListaItensPesquisadosAction;
		
		private global::Gtk.Action SobreOCatalogadorAction;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.MenuBar barraMenu;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button btnImportarDiretorio;
		
		private global::Gtk.ProgressBar pb;
		
		private global::Gtk.Entry edtPesquisa;
		
		private global::Gtk.Button btnPesquisa;
		
		private global::Gtk.VPaned spPesquisa;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.HPaned sp;
		
		private global::Gtk.ScrolledWindow scrollArvore;
		
		private global::Gtk.TreeView arvoreFixa;
		
		private global::Gtk.ScrolledWindow scrollTabelaFixa;
		
		private global::Gtk.NodeView tabelaFixa;
		
		private global::Gtk.Label labAbaFixa;
		
		private global::Gtk.ScrolledWindow scrollPesquisa;
		
		private global::Gtk.NodeView tabelaPesquisa;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Statusbar barraStatus1;
		
		private global::Gtk.Statusbar barraStatus2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget HFSGuardaDiretorio.gui.FrmPrincipal
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.AbaAction = new global::Gtk.Action ("AbaAction", global::Mono.Unix.Catalog.GetString ("Aba"), null, null);
			this.AbaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Aba");
			w1.Add (this.AbaAction, null);
			this.DiretorioAction = new global::Gtk.Action ("DiretorioAction", global::Mono.Unix.Catalog.GetString ("Diretório"), null, null);
			this.DiretorioAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Diretório");
			w1.Add (this.DiretorioAction, null);
			this.VisaoAction = new global::Gtk.Action ("VisaoAction", global::Mono.Unix.Catalog.GetString ("Visão"), null, null);
			this.VisaoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Visão");
			w1.Add (this.VisaoAction, null);
			this.SobreAction = new global::Gtk.Action ("SobreAction", global::Mono.Unix.Catalog.GetString ("Sobre"), null, null);
			this.SobreAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Sobre");
			w1.Add (this.SobreAction, null);
			this.IncluirNovaAbaAction = new global::Gtk.Action ("IncluirNovaAbaAction", global::Mono.Unix.Catalog.GetString ("Incluir Nova Aba"), null, null);
			this.IncluirNovaAbaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Incluir Nova Aba");
			w1.Add (this.IncluirNovaAbaAction, null);
			this.AlterarNomeDaAbaAtivaAction = new global::Gtk.Action ("AlterarNomeDaAbaAtivaAction", global::Mono.Unix.Catalog.GetString ("Alterar Nome da Aba Ativa"), null, null);
			this.AlterarNomeDaAbaAtivaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Alterar Nome da Aba Ativa");
			w1.Add (this.AlterarNomeDaAbaAtivaAction, null);
			this.ExcluirAbaAtivaAction = new global::Gtk.Action ("ExcluirAbaAtivaAction", global::Mono.Unix.Catalog.GetString ("Excluir Aba Ativa"), null, null);
			this.ExcluirAbaAtivaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Excluir Aba Ativa");
			w1.Add (this.ExcluirAbaAtivaAction, null);
			this.ImportarDiretorioAction = new global::Gtk.Action ("ImportarDiretorioAction", global::Mono.Unix.Catalog.GetString ("Importar Diretório"), null, null);
			this.ImportarDiretorioAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Importar Diretório");
			w1.Add (this.ImportarDiretorioAction, null);
			this.ImportarSubDiretoriosAction = new global::Gtk.Action ("ImportarSubDiretoriosAction", global::Mono.Unix.Catalog.GetString ("Importar SubDiretórios"), null, null);
			this.ImportarSubDiretoriosAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Importar SubDiretórios");
			w1.Add (this.ImportarSubDiretoriosAction, null);
			this.CompararDiretoriosAction = new global::Gtk.Action ("CompararDiretoriosAction", global::Mono.Unix.Catalog.GetString ("Comparar Diretórios"), null, null);
			this.CompararDiretoriosAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Comparar Diretórios");
			w1.Add (this.CompararDiretoriosAction, null);
			this.CadastrarExtensaoDeArquivoAction = new global::Gtk.Action ("CadastrarExtensaoDeArquivoAction", global::Mono.Unix.Catalog.GetString ("Cadastrar Extensão de Arquivo"), null, null);
			this.CadastrarExtensaoDeArquivoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cadastrar Extensão de Arquivo");
			w1.Add (this.CadastrarExtensaoDeArquivoAction, null);
			this.Action = new global::Gtk.Action ("Action", global::Mono.Unix.Catalog.GetString ("-"), null, null);
			this.Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("-");
			w1.Add (this.Action, null);
			this.ExpandirDiretoriosAction = new global::Gtk.Action ("ExpandirDiretoriosAction", global::Mono.Unix.Catalog.GetString ("Expandir Diretórios"), null, null);
			this.ExpandirDiretoriosAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Expandir Diretórios");
			w1.Add (this.ExpandirDiretoriosAction, null);
			this.ColapsarDiretoriosAction = new global::Gtk.Action ("ColapsarDiretoriosAction", global::Mono.Unix.Catalog.GetString ("Colapsar Diretórios"), null, null);
			this.ColapsarDiretoriosAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Colapsar Diretórios");
			w1.Add (this.ColapsarDiretoriosAction, null);
			this.ExportarDiretoriosDaAbaAtivaAction = new global::Gtk.Action ("ExportarDiretoriosDaAbaAtivaAction", global::Mono.Unix.Catalog.GetString ("Exportar Diretórios da Aba Ativa"), null, null);
			this.ExportarDiretoriosDaAbaAtivaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exportar Diretórios da Aba Ativa");
			w1.Add (this.ExportarDiretoriosDaAbaAtivaAction, null);
			this.ImportarDiretoriosViaXMLAction = new global::Gtk.Action ("ImportarDiretoriosViaXMLAction", global::Mono.Unix.Catalog.GetString ("Importar Diretórios via XML"), null, null);
			this.ImportarDiretoriosViaXMLAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Importar Diretórios via XML");
			w1.Add (this.ImportarDiretoriosViaXMLAction, null);
			this.GravarLogDaImportacaoAction = new global::Gtk.ToggleAction ("GravarLogDaImportacaoAction", global::Mono.Unix.Catalog.GetString ("Gravar Log da Importação"), null, null);
			this.GravarLogDaImportacaoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Gravar Log da Importação");
			w1.Add (this.GravarLogDaImportacaoAction, null);
			this.TXTAction = new global::Gtk.Action ("TXTAction", global::Mono.Unix.Catalog.GetString ("TXT"), null, null);
			this.TXTAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("TXT");
			w1.Add (this.TXTAction, null);
			this.TXTAction1 = new global::Gtk.Action ("TXTAction1", global::Mono.Unix.Catalog.GetString ("TXT"), null, null);
			this.TXTAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("TXT");
			w1.Add (this.TXTAction1, null);
			this.CSVAction = new global::Gtk.Action ("CSVAction", global::Mono.Unix.Catalog.GetString ("CSV"), null, null);
			this.CSVAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("CSV");
			w1.Add (this.CSVAction, null);
			this.HTMLAction = new global::Gtk.Action ("HTMLAction", global::Mono.Unix.Catalog.GetString ("HTML"), null, null);
			this.HTMLAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("HTML");
			w1.Add (this.HTMLAction, null);
			this.XMLAction = new global::Gtk.Action ("XMLAction", global::Mono.Unix.Catalog.GetString ("XML"), null, null);
			this.XMLAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("XML");
			w1.Add (this.XMLAction, null);
			this.SQLAction = new global::Gtk.Action ("SQLAction", global::Mono.Unix.Catalog.GetString ("SQL"), null, null);
			this.SQLAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("SQL");
			w1.Add (this.SQLAction, null);
			this.MostrarOcultarArvoreDirAbaAtivaAction = new global::Gtk.Action ("MostrarOcultarArvoreDirAbaAtivaAction", global::Mono.Unix.Catalog.GetString ("Mostrar/Ocultar árvore de diretórios da Aba Ativa"), null, null);
			this.MostrarOcultarArvoreDirAbaAtivaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Mostrar/Ocultar árvore de diretórios da Aba Ativa");
			w1.Add (this.MostrarOcultarArvoreDirAbaAtivaAction, null);
			this.MostrarOcultarListaItensPesquisadosAction = new global::Gtk.Action ("MostrarOcultarListaItensPesquisadosAction", global::Mono.Unix.Catalog.GetString ("Mostrar/Ocultar lista de itens pesquisados"), null, null);
			this.MostrarOcultarListaItensPesquisadosAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Mostrar/Ocultar lista de itens pesquisados");
			w1.Add (this.MostrarOcultarListaItensPesquisadosAction, null);
			this.SobreOCatalogadorAction = new global::Gtk.Action ("SobreOCatalogadorAction", global::Mono.Unix.Catalog.GetString ("Sobre o Catalogador"), null, null);
			this.SobreOCatalogadorAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Sobre o Catalogador");
			w1.Add (this.SobreOCatalogadorAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.WidthRequest = 900;
			this.HeightRequest = 500;
			this.Name = "HFSGuardaDiretorio.gui.FrmPrincipal";
			this.Title = global::Mono.Unix.Catalog.GetString ("HFSGuardaDiretorio 2.0 - Catalogador de Diretórios");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.DefaultWidth = 900;
			this.DefaultHeight = 500;
			// Container child HFSGuardaDiretorio.gui.FrmPrincipal.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name=\'barraMenu\'><menu name=\'AbaAction\' action=\'AbaAction\'><menuitem" +
			" name=\'IncluirNovaAbaAction\' action=\'IncluirNovaAbaAction\'/><menuitem name=\'Alte" +
			"rarNomeDaAbaAtivaAction\' action=\'AlterarNomeDaAbaAtivaAction\'/><menuitem name=\'E" +
			"xcluirAbaAtivaAction\' action=\'ExcluirAbaAtivaAction\'/></menu><menu name=\'Diretor" +
			"ioAction\' action=\'DiretorioAction\'><menuitem name=\'ImportarDiretorioAction\' acti" +
			"on=\'ImportarDiretorioAction\'/><menuitem name=\'ImportarSubDiretoriosAction\' actio" +
			"n=\'ImportarSubDiretoriosAction\'/><menuitem name=\'CompararDiretoriosAction\' actio" +
			"n=\'CompararDiretoriosAction\'/><menuitem name=\'CadastrarExtensaoDeArquivoAction\' " +
			"action=\'CadastrarExtensaoDeArquivoAction\'/><separator/><menuitem name=\'ExpandirD" +
			"iretoriosAction\' action=\'ExpandirDiretoriosAction\'/><menuitem name=\'ColapsarDire" +
			"toriosAction\' action=\'ColapsarDiretoriosAction\'/><menu name=\'ExportarDiretoriosD" +
			"aAbaAtivaAction\' action=\'ExportarDiretoriosDaAbaAtivaAction\'><menuitem name=\'TXT" +
			"Action1\' action=\'TXTAction1\'/><menuitem name=\'CSVAction\' action=\'CSVAction\'/><me" +
			"nuitem name=\'HTMLAction\' action=\'HTMLAction\'/><menuitem name=\'XMLAction\' action=" +
			"\'XMLAction\'/><menuitem name=\'SQLAction\' action=\'SQLAction\'/></menu><menuitem nam" +
			"e=\'ImportarDiretoriosViaXMLAction\' action=\'ImportarDiretoriosViaXMLAction\'/><men" +
			"uitem name=\'GravarLogDaImportacaoAction\' action=\'GravarLogDaImportacaoAction\'/><" +
			"/menu><menu name=\'VisaoAction\' action=\'VisaoAction\'><menuitem name=\'MostrarOcult" +
			"arArvoreDirAbaAtivaAction\' action=\'MostrarOcultarArvoreDirAbaAtivaAction\'/><menu" +
			"item name=\'MostrarOcultarListaItensPesquisadosAction\' action=\'MostrarOcultarList" +
			"aItensPesquisadosAction\'/></menu><menu name=\'SobreAction\' action=\'SobreAction\'><" +
			"menuitem name=\'SobreOCatalogadorAction\' action=\'SobreOCatalogadorAction\'/></menu" +
			"></menubar></ui>");
			this.barraMenu = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/barraMenu")));
			this.barraMenu.Name = "barraMenu";
			this.vbox1.Add (this.barraMenu);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.barraMenu]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnImportarDiretorio = new global::Gtk.Button ();
			this.btnImportarDiretorio.CanFocus = true;
			this.btnImportarDiretorio.Name = "btnImportarDiretorio";
			this.btnImportarDiretorio.UseUnderline = true;
			this.btnImportarDiretorio.Label = global::Mono.Unix.Catalog.GetString ("Importar Diretório");
			this.hbox1.Add (this.btnImportarDiretorio);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnImportarDiretorio]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.pb = new global::Gtk.ProgressBar ();
			this.pb.Name = "pb";
			this.hbox1.Add (this.pb);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.pb]));
			w4.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.edtPesquisa = new global::Gtk.Entry ();
			this.edtPesquisa.CanFocus = true;
			this.edtPesquisa.Name = "edtPesquisa";
			this.edtPesquisa.IsEditable = true;
			this.edtPesquisa.MaxLength = 255;
			this.edtPesquisa.InvisibleChar = '●';
			this.hbox1.Add (this.edtPesquisa);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.edtPesquisa]));
			w5.Position = 2;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnPesquisa = new global::Gtk.Button ();
			this.btnPesquisa.CanFocus = true;
			this.btnPesquisa.Name = "btnPesquisa";
			this.btnPesquisa.UseUnderline = true;
			this.btnPesquisa.Label = global::Mono.Unix.Catalog.GetString ("Pesquisar");
			this.hbox1.Add (this.btnPesquisa);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnPesquisa]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.spPesquisa = new global::Gtk.VPaned ();
			this.spPesquisa.CanFocus = true;
			this.spPesquisa.Name = "spPesquisa";
			this.spPesquisa.Position = 1;
			// Container child spPesquisa.Gtk.Paned+PanedChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			this.notebook1.Scrollable = true;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.sp = new global::Gtk.HPaned ();
			this.sp.CanFocus = true;
			this.sp.Name = "sp";
			this.sp.Position = 1;
			// Container child sp.Gtk.Paned+PanedChild
			this.scrollArvore = new global::Gtk.ScrolledWindow ();
			this.scrollArvore.Name = "scrollArvore";
			this.scrollArvore.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrollArvore.Gtk.Container+ContainerChild
			this.arvoreFixa = new global::Gtk.TreeView ();
			this.arvoreFixa.CanFocus = true;
			this.arvoreFixa.Name = "arvoreFixa";
			this.scrollArvore.Add (this.arvoreFixa);
			this.sp.Add (this.scrollArvore);
			global::Gtk.Paned.PanedChild w9 = ((global::Gtk.Paned.PanedChild)(this.sp [this.scrollArvore]));
			w9.Resize = false;
			// Container child sp.Gtk.Paned+PanedChild
			this.scrollTabelaFixa = new global::Gtk.ScrolledWindow ();
			this.scrollTabelaFixa.Name = "scrollTabelaFixa";
			this.scrollTabelaFixa.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrollTabelaFixa.Gtk.Container+ContainerChild
			this.tabelaFixa = new global::Gtk.NodeView ();
			this.tabelaFixa.CanFocus = true;
			this.tabelaFixa.Name = "tabelaFixa";
			this.scrollTabelaFixa.Add (this.tabelaFixa);
			this.sp.Add (this.scrollTabelaFixa);
			this.notebook1.Add (this.sp);
			// Notebook tab
			this.labAbaFixa = new global::Gtk.Label ();
			this.labAbaFixa.Name = "labAbaFixa";
			this.labAbaFixa.LabelProp = global::Mono.Unix.Catalog.GetString ("DISCO1");
			this.notebook1.SetTabLabel (this.sp, this.labAbaFixa);
			this.labAbaFixa.ShowAll ();
			this.spPesquisa.Add (this.notebook1);
			global::Gtk.Paned.PanedChild w13 = ((global::Gtk.Paned.PanedChild)(this.spPesquisa [this.notebook1]));
			w13.Resize = false;
			// Container child spPesquisa.Gtk.Paned+PanedChild
			this.scrollPesquisa = new global::Gtk.ScrolledWindow ();
			this.scrollPesquisa.Name = "scrollPesquisa";
			this.scrollPesquisa.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrollPesquisa.Gtk.Container+ContainerChild
			this.tabelaPesquisa = new global::Gtk.NodeView ();
			this.tabelaPesquisa.CanFocus = true;
			this.tabelaPesquisa.Name = "tabelaPesquisa";
			this.scrollPesquisa.Add (this.tabelaPesquisa);
			this.spPesquisa.Add (this.scrollPesquisa);
			this.vbox1.Add (this.spPesquisa);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.spPesquisa]));
			w16.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.barraStatus1 = new global::Gtk.Statusbar ();
			this.barraStatus1.Name = "barraStatus1";
			this.barraStatus1.Spacing = 6;
			this.barraStatus1.HasResizeGrip = false;
			this.hbox2.Add (this.barraStatus1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.barraStatus1]));
			w17.Position = 0;
			w17.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.barraStatus2 = new global::Gtk.Statusbar ();
			this.barraStatus2.Name = "barraStatus2";
			this.barraStatus2.Spacing = 6;
			this.hbox2.Add (this.barraStatus2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.barraStatus2]));
			w18.Position = 1;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w19.Position = 3;
			w19.Expand = false;
			w19.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.IncluirNovaAbaAction.Activated += new global::System.EventHandler (this.OnIncluirNovaAbaActionActivated);
			this.AlterarNomeDaAbaAtivaAction.Activated += new global::System.EventHandler (this.OnAlterarNomeDaAbaAtivaActionActivated);
			this.ExcluirAbaAtivaAction.Activated += new global::System.EventHandler (this.OnExcluirAbaAtivaActionActivated);
			this.ImportarDiretorioAction.Activated += new global::System.EventHandler (this.OnImportarDiretorioActionActivated);
			this.ImportarSubDiretoriosAction.Activated += new global::System.EventHandler (this.OnImportarSubDiretoriosActionActivated);
			this.CompararDiretoriosAction.Activated += new global::System.EventHandler (this.OnCompararDiretoriosActionActivated);
			this.CadastrarExtensaoDeArquivoAction.Activated += new global::System.EventHandler (this.OnCadastrarExtensaoDeArquivoActionActivated);
			this.ExpandirDiretoriosAction.Activated += new global::System.EventHandler (this.OnExpandirDiretoriosActionActivated);
			this.ColapsarDiretoriosAction.Activated += new global::System.EventHandler (this.OnColapsarDiretoriosActionActivated);
			this.ImportarDiretoriosViaXMLAction.Activated += new global::System.EventHandler (this.OnImportarDiretoriosViaXMLActionActivated);
			this.TXTAction1.Activated += new global::System.EventHandler (this.OnTXTAction1Activated);
			this.CSVAction.Activated += new global::System.EventHandler (this.OnCSVActionActivated);
			this.HTMLAction.Activated += new global::System.EventHandler (this.OnHTMLActionActivated);
			this.XMLAction.Activated += new global::System.EventHandler (this.OnXMLActionActivated);
			this.SQLAction.Activated += new global::System.EventHandler (this.OnSQLActionActivated);
			this.MostrarOcultarArvoreDirAbaAtivaAction.Activated += new global::System.EventHandler (this.OnMostrarOcultarArvoreDirAbaAtivaActionActivated);
			this.MostrarOcultarListaItensPesquisadosAction.Activated += new global::System.EventHandler (this.OnMostrarOcultarListaItensPesquisadosActionActivated);
			this.SobreOCatalogadorAction.Activated += new global::System.EventHandler (this.OnSobreOCatalogadorActionActivated);
			this.btnImportarDiretorio.Clicked += new global::System.EventHandler (this.OnBtnImportarDiretorioClicked);
			this.btnPesquisa.Clicked += new global::System.EventHandler (this.OnBtnPesquisaClicked);
			this.arvoreFixa.RowExpanded += new global::Gtk.RowExpandedHandler (this.OnArvoreFixaRowExpanded);
			this.arvoreFixa.RowCollapsed += new global::Gtk.RowCollapsedHandler (this.OnArvoreFixaRowCollapsed);
			this.arvoreFixa.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnArvoreFixaButtonReleaseEvent);
			this.tabelaFixa.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTabelaFixaRowActivated);
			this.tabelaFixa.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnTabelaFixaButtonReleaseEvent);
			this.tabelaPesquisa.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnTabelaPesquisaButtonReleaseEvent);
		}
	}
}
