# This file has been generated by the GUI designer. Do not modify.
module Stetic
	class Gui
		def initialize()
		end

		def Gui.Initialize(iconRenderer)
			if (Stetic.Gui.initialized == false) then
				Stetic.Gui.initialized = true
			end
		end
	end
	class ActionGroups
		def ActionGroups.GetActionGroup(type)
			return Stetic.ActionGroups.GetActionGroup(type.FullName)
		end

		def ActionGroups.GetActionGroup(name)
			return nil
		end
	end
end