# This file has been generated by the GUI designer. Do not modify.
module HFSGuardaDiretorio.gui
	class FrmSobre
		def initialize()
		end

		def Build()
			Stetic.Gui.Initialize(self)
			# Widget HFSGuardaDiretorio.gui.FrmSobre
			self.@Name = "HFSGuardaDiretorio.gui.FrmSobre"
			self.@Title = Mono.Unix.Catalog.GetString("Sobre o Catalogador")
			self.@WindowPosition = ((1))
			self.@Modal = true
			self.@Resizable = false
			self.@AllowGrow = false
			self.@DefaultWidth = 300
			self.@DefaultHeight = 150
			# Internal child HFSGuardaDiretorio.gui.FrmSobre.VBox
			w1 = self.@VBox
			w1.Name = "dialog1_VBox"
			w1.BorderWidth = ((2))
			# Container child dialog1_VBox.Gtk.Box+BoxChild
			self.@vbox2 = Gtk.VBox.new()
			self.@vbox2.Name = "vbox2"
			self.@vbox2.Spacing = 6
			# Container child vbox2.Gtk.Box+BoxChild
			self.@label1 = Gtk.Label.new()
			self.@label1.Name = "label1"
			self.@label1.LabelProp = Mono.Unix.Catalog.GetString("HFSGuardaDir 2.0 - Catalogador de Diretórios")
			self.@vbox2.Add(self.@label1)
			w2 = ((self.@vbox2[self.@label1]))
			w2.Position = 0
			w2.Expand = false
			w2.Fill = false
			# Container child vbox2.Gtk.Box+BoxChild
			self.@label2 = Gtk.Label.new()
			self.@label2.Name = "label2"
			self.@label2.LabelProp = Mono.Unix.Catalog.GetString("Desenvolvido em C# com GTK#, Versão: 2.0")
			self.@vbox2.Add(self.@label2)
			w3 = ((self.@vbox2[self.@label2]))
			w3.Position = 1
			w3.Expand = false
			w3.Fill = false
			# Container child vbox2.Gtk.Box+BoxChild
			self.@label3 = Gtk.Label.new()
			self.@label3.Name = "label3"
			self.@label3.LabelProp = Mono.Unix.Catalog.GetString("Por Henrique Figueiredo de Souza")
			self.@vbox2.Add(self.@label3)
			w4 = ((self.@vbox2[self.@label3]))
			w4.Position = 2
			w4.Expand = false
			w4.Fill = false
			# Container child vbox2.Gtk.Box+BoxChild
			self.@label4 = Gtk.Label.new()
			self.@label4.Name = "label4"
			self.@label4.LabelProp = Mono.Unix.Catalog.GetString("Todos os direitos reservados, 2014")
			self.@vbox2.Add(self.@label4)
			w5 = ((self.@vbox2[self.@label4]))
			w5.Position = 3
			w5.Expand = false
			w5.Fill = false
			w1.Add(self.@vbox2)
			w6 = ((w1[self.@vbox2]))
			w6.Position = 0
			w6.Expand = false
			w6.Fill = false
			# Internal child HFSGuardaDiretorio.gui.FrmSobre.ActionArea
			w7 = self.@ActionArea
			w7.Name = "dialog1_ActionArea"
			w7.Spacing = 10
			w7.BorderWidth = ((5))
			w7.LayoutStyle = ((1))
			# Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			self.@buttonOk = Gtk.Button.new()
			self.@buttonOk.CanDefault = true
			self.@buttonOk.CanFocus = true
			self.@buttonOk.Name = "buttonOk"
			self.@buttonOk.UseStock = true
			self.@buttonOk.UseUnderline = true
			self.@buttonOk.Label = "gtk-ok"
			self.AddActionWidget(self.@buttonOk, -5)
			w8 = ((w7[self.@buttonOk]))
			w8.Expand = false
			w8.Fill = false
			if (self.@Child != nil) then
				self.@Child.ShowAll()
			end
			self.Show()
			self.@buttonOk.Clicked { |sender, e| self.@OnButtonOkClicked(sender, e) }
		end
	end
end